dwarvesf/memo.d.foundation

- assets/js/markdown-entities.js
- assets/scss/partials/header.scss
- assets/scss/partials/note-content.scss
- assets/scss/reset.scss
- layouts/partials/footer.html
- layouts/partials/header.html
> fix: overflow issues and replace markdown bold pattern

- assets/scss/partials/note-content.scss
- assets/scss/reset.scss
> fix: code snippet styling

- assets/scss/partials/note-content.scss
- assets/scss/reset.scss
> fix: code snippets overflow styling

- assets/scss/reset.scss
> fix: prevent code snippets from scrolling vertically

- .vscode/settings.json
- assets/js/dark-light-check.js
- assets/scss/link.scss
- assets/scss/partials/footer.scss
- assets/scss/partials/header.scss
- assets/scss/partials/menu.scss
- assets/scss/partials/note-content.scss
- assets/scss/reset.scss
- assets/scss/styles.scss
- layouts/partials/footer.html
- layouts/partials/header.html
- layouts/partials/menu.html
- layouts/partials/tab-menu.html
> feat: dark mode toggler, move footer to sidebar and ui enhancement

- assets/js/graph.js
- assets/scss/graph.scss
- assets/scss/partials/note-content.scss
- assets/scss/reset.scss
- assets/scss/styles.scss
- layouts/partials/header.html
> feat: add realted graph to page navbar

- assets/js/reading-tooltip.js
- assets/scss/partials/header.scss
- layouts/partials/header.html
> fix: reading mode tooltip

- assets/js/table-of-contents.js
- assets/scss/partials/table-of-contents.scss
- assets/scss/styles.scss
> fix: table of content

- assets/js/init.js
- assets/scss/variables.scss
- layouts/partials/header.html
Using one-dark/light theme and also use IBM+Plex+Mono font (ref gitbook)
> fix: make code theme more visible

- assets/js/single.js
- assets/scss/partials/single.scss
- assets/scss/partials/toastify.scss
- assets/scss/reset.scss
- assets/scss/styles.scss
- assets/scss/variables.scss
- layouts/_default/single.html
- layouts/partials/header.html
- layouts/partials/subscription.html
> feat: add sub block and toastify

- assets/scss/partials/toastify.scss
- layouts/partials/command-palette.html
https://github.com/user-attachments/assets/59de3c3f-ca0c-488c-9114-95597cc67778
> fix: use toastify in search

- assets/js/single.js
- assets/scss/partials/single.scss
- layouts/_default/single.html
- layouts/partials/mentioned.html
https://github.com/user-attachments/assets/76d39e89-23b5-42df-81ac-5eec75679a95
> feat: add mentioned in block

- assets/js/sidebar-tooltip.js
- assets/scss/partials/command-palette.scss
- assets/scss/partials/footer.scss
- assets/scss/partials/header.scss
- assets/scss/partials/note-content.scss
- assets/scss/partials/sidebar.scss
- assets/scss/partials/single.scss
- layouts/partials/command-palette.html
- layouts/partials/header.html
- layouts/partials/sidebar.html
> fix: sidebar

- assets/js/table-of-contents.js
- assets/scss/partials/note-content.scss
- assets/scss/partials/table-of-contents.scss
- layouts/partials/header.html
> fix: right nav spacing off & scrolling stuck

- assets/js/query-engine.mjs
- layouts/partials/command-palette.html
> fix: command menu placeholder

- assets/scss/partials/footnote.scss
- assets/scss/styles.scss
> feat: update footnote style

- assets/scss/featured-posts.scss
- assets/scss/link.scss
- assets/scss/partials/command-palette.scss
- assets/scss/partials/footer.scss
- assets/scss/partials/header.scss
- assets/scss/partials/home.scss
- assets/scss/partials/menu.scss
- assets/scss/partials/note-content.scss
- assets/scss/partials/recents.scss
- assets/scss/variables.scss
- refactor home style selector
- update `secondary-font-color-light`secondary-font-color-light-2`
> fix: refactor home style selector and secondary color

- assets/scss/partials/home.scss
https://www.loom.com/share/540534075c7e460eb74c84b97a12973d
> fix: new memo section responsive

- assets/js/table-of-contents.js
- assets/scss/partials/menu.scss
- assets/scss/partials/note-content.scss
- assets/scss/partials/table-of-contents.scss
- fix: click ToC item
- fix: flick layout when toggling reading mode
- fix: page nav show animation
- fix: ToC scrolling
https://www.loom.com/share/85faf37e9f6d4cc2ada86af652776096
> fix: main layout

- layouts/_default/list.html
- layouts/partials/header.html
> feat: support link for location

- assets/scss/404.scss
- assets/scss/mixins.scss
- assets/scss/neko.scss
- assets/scss/overlay.scss
- assets/scss/partials/header.scss
- assets/scss/partials/home.scss
- assets/scss/partials/menu.scss
- assets/scss/partials/note-content.scss
- assets/scss/partials/sidebar.scss
- assets/scss/partials/table-of-contents.scss
- assets/scss/reset.scss
- assets/scss/styles.scss
- layouts/_default/index.html
- layouts/_default/list.html
- layouts/_default/single.html
- layouts/partials/processed-content.html
https://www.loom.com/share/ffda45ea4218461caba3ceac97f7f34a
> fix: layout shift while toggling reading mode

- layouts/partials/processed-content.html
Test code:
```Transform symbol:
- Right arrow: -> →
- Left arrow: <- ←
- Implies: => ⇒
- Implies backwards: <= ⇐
- If and only if: <=> ⇔
- Long arrow: --> ⟶
- Greater than or equal to: >= ≥
- Less than or equal to: <= ≤
- Equivalent to: == ≡
- Not equal to: != ≠
Native support
- Em dash: -- —
- Ellipsis: ... …
- Curly quotes: 'single' "double" “ ”
- Much less than: << ≪
- Much greater than: >> ≫
Preserve symbol in code block:
```mermaid
aaa -->bbb
```
`
> feat: transform symbol

- package.json
- pnpm-lock.yaml
- src/components/layout/DirectoryTree.tsx
- src/components/layout/RootLayout.tsx
- src/lib/content/directoryTree.ts
- src/lib/content/search.ts
- src/lib/content/utils.ts
- src/lib/utils.ts
- src/pages/[...slug].tsx
- src/pages/index.tsx
- src/styles/globals.css
- src/types/index.ts
https://www.loom.com/share/431ea46f3da2488fae69a392256428f5
> feat: directory tree

- src/components/layout/RootLayout.tsx
- src/hooks/useScrollToTopOnRouteChange.ts
https://www.loom.com/share/5cf33c6d598e40f09fd46f8414bca81c
> fix: scroll top on route change

- src/lib/content/markdown.ts
This PR fixes an issue where internal markdown links were being rendered with an unnecessary `.md` suffix in the final HTML output. For example, a link like `[Moonlighting](moonlighting.md)` would navigate to `http://localhost:3000/handbook/moonlighting.md` instead of the correct `http://localhost:3000/handbook/moonlighting`.
- Added a custom `remarkProcessLinks` plugin that detects and processes relative markdown links
- The plugin removes the `.md` extension from links that end with `.md` and are not external links
- Integrated the plugin into the markdown processing pipeline before the conversion to HTML
- Added proper TypeScript typing for the link nodes
- Internal markdown links now navigate to the correct paths without the `.md` extension
- External links and links without the `.md` …
> fix: remove .md extension from internal markdown links

- src/lib/content/backlinks.ts
This PR improves the backlinks search functionality in the memo.d.foundation platform by enhancing the pattern matching and search capabilities.
- Added support for both original and slugified versions in content search
- Enhanced pattern matching for backlink detection to improve accuracy
- Improved filtering of entries with empty title or description
- Optimized search patterns to catch more valid backlink references
The changes primarily focus on the `src/lib/content/backlinks.ts` file, where we've:
1. Enhanced the content search to check for both original and slugified versions of paths
2. Added additional pattern matching for backlink detection using prefixes ('/' and '#')
3. Improved the filtering logic to skip entries with empty title or description
4. Maintained backward …
> feat(backlinks): improve search patterns for backlinks

- src/lib/content/backlinks.ts
This PR improves the backlink search functionality in the memo.d.foundation platform by enhancing the pattern matching and filtering logic.
- Added support for both original and slugified path matching in backlink detection
- Enhanced regex patterns for more accurate backlink detection
- Improved filtering logic for backlink entries to ensure better quality results
The changes focus on the `getBacklinks` function in `src/lib/content/backlinks.ts`, where we:
1. Now handle both original and slugified versions of paths and slugs
2. Improved the regex patterns to better match memo.d.foundation URLs
3. Enhanced the filtering logic to ensure we only return valid backlinks
The changes have been tested with various scenarios including:
- URLs with and without trailing slashes
- Paths with special …
> feat(backlinks): improve backlink search patterns

- src/components/layout/CommandPalette.tsx
- src/components/layout/CommandPaletteModal.tsx
- src/components/layout/RightSidebar.tsx
- src/components/layout/SubscriptionSection.tsx
- src/components/layout/TableOfContents.tsx
- src/styles/globals.css
- src/styles/markdown.css
- tailwind.config.mjs
- https://www.notion.so/dwarves/Memo-clean-up-1c964b29b84c809992f6fe7c0aeccb72?p=1c964b29b84c8062bb22ff007d796e56&pm=s
- https://www.loom.com/share/2c90d6e5ae7b4681a97a214e251214df
> fix: single page

- src/components/layout/DirectoryTree.tsx
This PR fixes the directory tree highlighting behavior to improve visual clarity and consistency:
- Removed both text and line highlighting from all expandable directory groups
- Groups that can be clicked and expanded (hasChildren) will no longer show:
- Pink text highlighting
- Pink vertical line highlighting
- This applies to all levels of the directory tree, not just root groups
Previously, expandable groups like "Consulting" or "Hiring" would show highlighting when:
- On their root/index pages
- When viewing their readme files
- When viewing their child pages
This created visual confusion as both the parent group and current item would be highlighted.
Now:
- Only actual content items can be highlighted
- Expandable groups never show highlighting
- Vertical line highlighting only …
> fix: remove highlighting from expandable directory groups

- src/components/layout/SubscriptionSection.tsx
- src/components/memo/MemoVList.tsx
- src/lib/content/directoryTree.ts
- src/lib/utils.ts
- src/styles/markdown.css
- subscription form font family: arial,serif
- fix: memo list author link
- missing space in blockquote and after h2
- remove heading link hightlight
- uppercase directory tree words: nda, aarrr, wala
> fix: misc 2

- src/components/layout/DirectoryTree.tsx
> feat: add animation for active item menu

- src/components/layout/CommandPalette.tsx
- src/components/layout/RightSidebar.tsx
- src/lib/content/markdown.ts
- src/pages/404.tsx
- src/styles/markdown.css
- fix: render video
- fix: 404 page mobile styling
- fix: header id
- fix: right sizebar width
- fix:  remove margin top of first p element in li tag
https://www.loom.com/share/9fd430eb7da64b3687a02f9eaa1b1d6b
> fix: misc 3

- package.json
- pnpm-lock.yaml
- src/components/RenderMarkdown.tsx
- src/components/layout/CommandPaletteModal.tsx
- src/components/search/SearchProvider.tsx
https://www.loom.com/share/1d31567212484dad8f4643f4c6011a13
> feat: render search preview markdown content

- src/components/layout/ContentLayout.tsx
- src/components/layout/RightSidebar.tsx
- src/lib/content/directoryTree.ts
- src/lib/utils.ts
- src/pages/tags/[slug].tsx
> fix: uppercase tag special words

- src/components/layout/CommandPalette.tsx
- src/lib/content/markdown.ts
- src/lib/utils.ts
- src/pages/[...slug].tsx
- fix command palette style
- fix directory tree lowercase
- fix: block count
> fix: styling

- src/lib/content/markdown.ts
> fix: blockcount

- src/components/layout/Footer.tsx
> feat: add rss to footer

- package.json
- pnpm-lock.yaml
- src/components/layout/CommandPalette.tsx
- src/components/layout/CommandPaletteModal.tsx
- src/components/layout/CommandSearchInput.tsx
https://www.loom.com/share/f475bab2e863451bb91e9b1c52addae7
> fix: search single line

- src/components/layout/RootLayout.tsx
- src/components/layout/SubscriptionSection.tsx
- src/components/layout/UtterancComments.tsx
- src/styles/globals.css
- fix: Keep comment box in full width
- fix: ctr shift f to toggle reading mode
- fix: refresh comment script after changing pathname 
- https://www.notion.so/dwarves/1d564b29b84c80559c45c288c97273e1?v=1d564b29b84c80bdbcde000c13abfb6b&p=1d864b29b84c80eba711c2531d20ba71&pm=s
- https://www.notion.so/dwarves/1d564b29b84c80559c45c288c97273e1?v=1d564b29b84c80bdbcde000c13abfb6b&p=1d964b29b84c80739671d26e4e32494c&pm=s
https://www.loom.com/share/75e5df42588744718b46e36268bbec27
> fix: comment section

- src/components/image/ImageFullScreenModal.tsx
- src/components/layout/CommandPalette.tsx
- src/components/layout/RootLayout.tsx
https://www.loom.com/share/ffca5a63a20f4102986d85864d04a800
> fix: shortcut not work on safari

- src/styles/globals.css
- tailwind.config.mjs
> fix: decrease text size to 15px

- src/components/layout/ContentLayout.tsx
- src/components/memo/SummaryBlock.tsx
- src/lib/content/markdown.ts
- src/pages/[...slug].tsx
- src/styles/globals.css
- src/types/index.ts
> feat: memo summary

- src/components/layout/CommandPalette.tsx
- src/components/search/SearchProvider.tsx
- src/contexts/theme.tsx
- fix: theme flashing on first load
- fix: search sorting
- fix: search recent items
- https://www.loom.com/share/da0ad8d2ea40496eb2d1f3502284bb52
> fix: theme flashing  and search sorting 

- src/components/layout/DirectoryTree.tsx
- src/lib/content/utils.ts
> feat: popular tags

- scripts/generate-user-profiles.ts
- src/types/user.ts
// Put in link to Git Issue
// Use [Licecap](http://www.cockos.com/licecap/) to share a screencast gif.
- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new dependencies which need to be added to?
> fix: types

- src/components/RemoteMdxRenderer.tsx
- src/components/layout/CommandPalette.tsx
- src/components/memo/utils.ts
- src/lib/content/memo.ts
- src/lib/content/utils.ts
- src/pages/index.tsx
- src/styles/components.css
- src/styles/globals.css
- src/types/index.ts
- render home page mdx (index.mdx)
- fix recent pages in home page
> feat: mdx home page

- scripts/generate-user-profiles.ts
- src/lib/content/memo.ts
// Put in link to Git Issue
// Use [Licecap](http://www.cockos.com/licecap/) to share a screencast gif.
- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new dependencies which need to be added to?
> fix: convert all tags to string

- src/styles/globals.css
https://github.com/dwarvesf/memo.d.foundation/issues/162
> fix: x-scroll on safari mobile

- src/components/RemoteMdxRenderer.tsx
- src/components/common/Choose.tsx
- src/components/common/If.tsx
In MDX, using {} for conditional rendering prevents Markdown content inside from being parsed correctly. To handle this, I created If and Choose components (inspired by [react-extras](https://github.com/sindresorhus/react-extras)) for conditional rendering while preserving Markdown formatting.
Inper
> feat: add logical components

- eslint.config.mjs
- src/components/layout/CommandPalette.tsx
- src/contexts/Web3Provider.tsx
- src/pages/[...slug].tsx
- src/types/type.d.ts
- src/types/utils.d.ts
Use the shortest link from the redirect in the frontmatter as the share link.
> feat: take shortest link as share link

- scripts/generate-redirects.ts
> fix: remove symbols for alias generate

- scripts/generate-redirects.ts
> chore: add initial aliases

- src/pages/[...slug].tsx
> fix: image on readme

- .github/workflows/generate-redirects.yml
> fix: ci redirects

- docs/adr/0008-unify-url-path-resolution.md
- docs/changelog/0002-unify-url-path-resolution-and-redirects.md
- docs/specs/0004-unified-url-path-resolution-system.md
- src/components/layout/CommandPalette.tsx
- src/lib/content/markdown.ts
- src/lib/content/paths.ts
- src/lib/content/utils.ts
- src/lib/utils/path-utils.ts
- src/pages/[...slug].tsx
- src/pages/_document.tsx
> fix: missed replacing place url

- src/components/layout/Header.tsx
> refactor: update header component 2

- src/components/layout/DirectoryTree.tsx
- src/components/layout/RightSidebar.tsx
- src/components/layout/RootLayout.tsx
> style: adjust padding layout

- .github/workflows/add-mint-post.yml
- .github/workflows/deploy-arweave.yml
- .github/workflows/generate-redirects.yml
- package.json
- pnpm-lock.yaml
- src/lib/prompts.ts
- src/types/index.ts
> fix: build from gh actions

- src/lib/content/tags-utils.ts
- src/pages/tags/index.tsx
> feat: grid display for tags page

- public/assets/img/arrow-right.svg
- src/lib/content/markdown.ts
- src/lib/mdx.ts
- src/styles/markdown.css
> feat: list styling

- Dockerfile
- docs/changelog/0005-refactor-link-utils-duplication.md
- lib/obsidian-compiler/lib/memo/common/link_utils.ex
- src/lib/content/markdown.ts
- src/lib/mdx.ts
> fix: add handler for url in mdx

- .github/workflows/generate-redirects.yml
- Makefile
- README.md
- docs/adr/0011-0011-git-submodule-hook-manager.md
- docs/adr/0012-0012-modular-markdown-linting-system.md
- docs/changelog/0006-git-submodule-hook-manager.md
- docs/changelog/0007-modular-markdown-linting-system.md
- docs/specs/0009-git-submodule-hook-manager.md
- docs/specs/0010-modular-markdown-linting-system.md
- nginx/nginx.custom.conf
- package.json
- pnpm-lock.yaml
- scripts/formatter/ci-lint.js
- scripts/formatter/ci-lint.ts
- scripts/formatter/note-lint.js
- scripts/formatter/note-lint.ts
- scripts/formatter/rules/frontmatter.js
- scripts/formatter/rules/frontmatter.ts
- scripts/formatter/rules/index.js
- scripts/formatter/rules/index.ts
- scripts/formatter/rules/no-heading1.js
- scripts/formatter/rules/no-heading1.ts
- scripts/formatter/rules/relative-link-exists.js
- scripts/formatter/rules/relative-link-exists.ts
- scripts/formatter/rules/types.ts
- scripts/git-shell-hook.ts
- tsup.config.ts
-----------
Pre-commit linting:
----------
Available tool should can be found at this path:
`/tools/ci-lint.js` -> Eg: https://memo.d.foundation/tools/ci-lint.js
> ci: script hook

- src/components/layout/CommandPalette.tsx
- src/components/layout/CommandPaletteModal.tsx
- src/styles/globals.css
> refactor: mobile command palette improvements

- src/components/layout/PageTableOfContents.tsx
- src/components/layout/TableOfContents.tsx
Handle heading id url recording like https://memo.d.foundation/arc/on-agent#how-were-upgrading
> fix: missing heading id in url

- next.config.ts
- package.json
- scripts/generate-static-paths.ts
- src/lib/content/memo.ts
- src/lib/content/paths.ts
- src/lib/content/utils.ts
- src/lib/memory-cache.ts
Development environment first load initially ~ 12s, next load ~1-2s
> pref: add pre-generated static paths

- .github/workflows/dispatch.yml
- docs/adr/0013-replace-mtime-with-git-timestamps-for-incremental-.md
- docs/changelog/0008-fix-git-timestamp-based-incremental-processing.md
- lib/obsidian-compiler/lib/memo/export_duckdb.ex
> ci: fix processed time causing filter out the files

- .github/workflows/generate-redirects.yml
- scripts/generate-redirects.ts
- With newly added files:
https://github.com/dwarvesf/memo.d.foundation/actions/runs/16064936277/job/45337565744
- Without changed:
https://github.com/dwarvesf/memo.d.foundation/actions/runs/16064968575/job/45337651834
> ci: update logic get changed files

- package.json
- pnpm-lock.yaml
- src/lib/content/markdown.ts
- src/pages/_app.tsx
Resolved https://github.com/dwarvesf/memo.d.foundation/issues/278
> feat: include link target to headings

- scripts/generate-search-index.ts
> chore: add keywords match filename

- memory-bank/raw_reflection_log.md
- package.json
- pnpm-lock.yaml
- scripts/formatter/ci-lint.ts
- scripts/formatter/note-lint.ts
- scripts/formatter/rules/index.ts
- scripts/formatter/rules/sentence-case.ts
- scripts/git-shell-hook.ts
- tsup.config.ts
> ci: update markdown lint gh
